### ISSUE TITLE
having error of file location

### ISSUE THREAD

**Issue by ashubansal005** [AquibPy/Face-Emotions-Detection-Using-CNN#1]
File b'FER-2013.csv' does not exist

help pls

**Comment by AquibPy** [comment]
Just go to ReadMe sections 
And read Basic usage i have provided download link


https://drive.google.com/file/d/1X60B-uR3NtqPd4oosdotpbDgy8KOfUdr/view?usp=sharing

**Comment by AquibPy** [comment]
https://drive.google.com/file/d/1X60B-uR3NtqPd4oosdotpbDgy8KOfUdr/view?usp=sharing



Actually kaggle has deleted the dataset.You can download form here unzip
the file u will get csv.

**Comment by ashubansal005** [comment]
I am using OpenCV 4.2, I think some functions are changed, that's why I am facing an error.

**Comment by AquibPy** [comment]
Mail me your source code.
Which python version you are using?

**Comment by ashubansal005** [comment]
same code as you have.
and have python 3.6

**Comment by AquibPy** [comment]
Try to run on python 3.7 .may be your error will resolve.

What type of error it is giving?

**Comment by AquibPy** [comment]
i have modified the code now it will run easily.
Note:  Kindly install tensorflow and python 3.7

**Comment by ashubansal005** [comment]
Thanks for your help but
i have facing the same error.

**Comment by ashubansal005** [comment]
[Errno 2] File fer2013.csv does not exist: 'fer2013.csv'

how the image file excess CSV format

**Comment by ashubansal005** [comment]
and in app.py file error is this  No module named 'cv2.cv2'

**Comment by AquibPy** [comment]
for CSV kindly download the dataset, I have provided a link in Readme Section.
unzip the file you will get the CSV of size approx 287mb.
In CSV there are different pixels for different emotions and we are dealing with then and putting in convolution neural net.

And for this error No module named 'cv2.cv2', this is popping up because you have not installed OpenCV in this environment.

**Comment by ashubansal005** [comment]
still not worked i am trying but not able to solve all errors

ImportError: DLL load failed: The specified module could not be found.
Failed to load the native TensorFlow runtime.

i am not find a 287mb file in the readme section yet I already downloaded all.
will you pls provide that file link.

**Comment by ashubansal005** [comment]
when i run app.py i found this eror

OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\objdetect\src\cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'cv::CascadeClassifier::detectMultiScale'
but webcam  is on

**Comment by ashubansal005** [comment]
i installed tensorflow by make an new environment in anaconda and run this cmd on anaconda prompt
>pip install tensorflow==2.0.0b1
 I have successfully installed opencv

**Comment by AquibPy** [comment]
https://drive.google.com/file/d/1X60B-uR3NtqPd4oosdotpbDgy8KOfUdr/view?usp=sharing. 

Download dataset from 👆 and in csv there are pixels for different emotion not images.
And delete all the conda environment then open anaconda command prompt and paste this command

conda create -n tensorflow_env tensorflow
After installing tensorflow 
Activate the environment  using
conda activate tensorflow_env

Then Install the remaining library in this environment using pip

**Comment by ashubansal005** [comment]
the dataset that you have shared have shared having 60 MB file which contain images, of train and test folder .

**Comment by AquibPy** [comment]
Bro i am really sorry i think i have pasted wrong link.

https://drive.google.com/file/d/18rQxzx2jyUzisuqFq9XHmhFxUkAf1Lu9/view?usp=sharing
check this link

**Comment by ashubansal005** [comment]
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.
bro I think I am done with this I am not able to run the code. i am tired for trying this.

**Comment by AquibPy** [comment]
ok don't know why it is not running in your pc

**Comment by ashubansal005** [comment]
![Screenshot (104)](https://user-images.githubusercontent.com/35791707/87663004-c39fea00-c780-11ea-9be6-0eb3e02618ab.png)
bro finally model is trained, but now the new error is showing. 
what I further do? please help!

**Comment by AquibPy** [comment]
error is related to plotting why are u plotting graph?
if it is required try in jupyter notebook
or mail me your emotion.py file at mohdaquib31@gmail.com for further issue as i have not done any plotting in my code.

**Comment by AquibPy** [comment]
metrices = pd.DataFrame(model.history.history)
# for plot b/t loss and val_loss
metrices[['loss','val_loss']].plot()

# for plot b/w accuracy & val_accuracy
metrices[['accuracy','val_accuracy']].plot()

note: name of my model is 'model' that's why I use model.history.history
if you use another name try yourModelName.history.history


### also your model is towards overfitting try to optimise it

**Comment by ashubansal005** [comment]
bro, will you please make a small video for me. about how to implement emotion detection on jupyter.and also which version of python, Keras, TensorFlow, OpenCV are you using in it.

**Comment by AquibPy** [comment]
Mail me your whatsapp number so that i can communicate with you easily
